version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.production
    restart: always
    ports:
      - "5432:5432"

  petfinder:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ver1
    container_name: petfinder
    volumes:
      - .:/petfinder
    stdin_open: true
    tty: true
    env_file: .env.production
    environment:
      RAILS_ENV: production
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b
      '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    external: true
  petfinder_volume:
networks:
  development:
  test:
