version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    container_name: frontend
    image: frontend
    ports:
      - "3300:3300"
    volumes:
      # - ./:/frontend:delegated
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
