FROM node:19-alpine AS builder
RUN mkdir app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
RUN apk update && apk upgrade \
  && apk -U add --no-cache sudo bash && npm install -g npm@latest

ADD frontend ./
RUN npm install --silent
RUN npm run build

FROM scratch AS export-stage
COPY --from=builder /app/build .


