FROM node:19-alpine AS builder
RUN mkdir app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
RUN apk -U add --no-cache sudo bash && apk update && apk upgrade && npm install -g npm@latest

ADD ./frontend/package.json ./
RUN npm install --silent

EXPOSE 3300
CMD [ "npm", "start" ]



