FROM node:19-alpine AS builder
RUN mkdir app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
RUN apk update && apk upgrade apk -U add --no-cache sudo bash && npm install -g npm@latest

ADD ./frontend/package.json ./
RUN npm install --silent

EXPOSE 3000
CMD [ "npm", "start" ]
# CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true



