version: "3.8"

volumes:
  shared_data:

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend
    volumes:
      - .:/pet-finder
      - shared_data:/var/shared
    # environment:
    # DOCKER_BUILDKIT: 1
